import type { Copy, Language } from './types';

export const toothLabels = [
  'Top right back',
  'Top right middle',
  'Top front right',
  'Top front left',
  'Top left middle',
  'Top left back',
  'Bottom left back',
  'Bottom left middle',
  'Bottom front left',
  'Bottom front right',
  'Bottom right middle',
  'Bottom right back',
];

export const copyByLanguage: Record<Language, Copy> = {
  en: {
    appName: 'SmileSteps',
    tagline: 'Healthy smile habits for kids, teens, and parents.',
    heroTitle: 'Small routines, stronger smiles',
    heroBody:
      'SmileSteps is a local-first proof of concept for pediatric dental and orthodontic routines. Everything here stays on this device unless you choose otherwise in a future version.',
    createProfile: 'Create profile',
    languageLabel: 'App language',
    parentView: 'Parent view',
    childView: 'Kid view',
    tabs: {
      home: 'Home',
      brushing: 'Brush',
      track: 'Track',
      learn: 'Learn',
      parent: 'Parent',
    },
    home: {
      welcome: 'Today is a great day to take care of your smile.',
      dailyPlan: 'Pick one small win: brush, log a tooth update, track aligner time, or learn something new.',
      startHereTitle: 'Start here',
      startHereBody: 'This demo works best like a mobile app. Pick a profile, choose one quick task, and move through the tabs at the bottom.',
      nextSteps: ['\u2728 Brush for 2 minutes', '\uD83E\uDDB7 Update a tooth milestone', '\u23F1\uFE0F Track aligner time', '\uD83D\uDCA1 Learn one new tool'],
      onboardingTitle: 'Welcome to SmileSteps',
      onboardingBody: 'This is a calm, kid-friendly place for brushing habits, tooth milestones, and orthodontic routines.',
      onboardingPoints: [
        'Choose a kid or teen profile.',
        'Use the brush screen for a guided 2-minute routine.',
        'Tap through teeth, ortho, and learn at your own pace.',
      ],
      onboardingButton: 'Let’s begin',
      tasksTitle: 'Today’s tasks',
      activityTitle: 'Recent activity',
      emptyActivity: 'Your recent smile updates will show up here.',
      timerCard: 'Start a 2-minute brushing session with upbeat coaching.',
      toothCard: 'Track baby teeth, permanent teeth, and fun smile milestones.',
      orthoCard: 'Keep aligner routines steady with simple reminders and progress.',
      learnCard: 'Explore calm, kid-friendly explainers about common dental tools.',
    },
    brushing: {
      title: '2-minute brushing timer',
      body: 'Move slowly, switch sides when prompted, and aim for gentle circles.',
      start: '\u25B6\uFE0F Start',
      reset: '\uD83D\uDD04 Reset',
      pause: '\u23F8\uFE0F Pause',
      resume: '\u25B6\uFE0F Resume',
      finished: '\uD83C\uDF89 Nice work! Two minutes complete.',
      encouragement: ['\u2B55 Tiny circles', '\uD83D\uDE01 Front teeth time', '\uD83E\uDDB7 Chewing surfaces next', '\uD83D\uDCAA Almost there', '\u2728 Sparkly finish'],
      quadrants: ['\u2196\uFE0F Top right', '\u2197\uFE0F Top left', '\u2199\uFE0F Bottom left', '\u2198\uFE0F Bottom right'],
      helperFinished: 'You finished every section of your smile.',
      helperPrefix: 'Focus on',
      helperSuffix: 'with gentle circles.',
    },
    teeth: {
      title: 'Tooth tracker',
      body: 'Tap a spot to mark a baby tooth that has wiggled out or to clear it again.',
      hint: 'This tracker is for family education only and does not give medical advice.',
      labels: toothLabels,
    },
    ortho: {
      title: 'Orthodontic habits',
      body: 'Track aligner hours and keep tray changes from sneaking up on you.',
      goal: 'Goal hours today',
      nextChange: 'Next tray change',
      progressTitle: 'Today’s progress',
      progressStates: {
        strong: '\uD83D\uDCAA Strong routine',
        steady: '\uD83D\uDCC8 Steady progress',
        needsCare: '\uD83D\uDD04 Needs a reset',
      },
      nextChangeLabels: {
        today: '\uD83D\uDD34 Tray change is today',
        tomorrow: '\uD83D\uDFE1 Tray change is tomorrow',
        inDaysPrefix: '\u23F3 Days until next change',
        overdue: '\u26A0\uFE0F Tray change has passed',
      },
      historyTitle: '\uD83D\uDCCB Recent ortho activity',
      emptyHistory: 'Your aligner and tray-change updates will show here.',
      remindersTitle: 'Helpful reminders',
      reminders: [
        'Wear aligners as directed by your orthodontic team.',
        'Take them out for meals unless your orthodontist says otherwise.',
        'Use the case instead of wrapping them in a napkin.',
      ],
      comfortTitle: '\uD83D\uDEDF Comfort tips',
      comfortTips: [
        'Use a fresh case so aligners stay clean.',
        'Cold water can feel soothing after a tray change.',
        'Take aligners out before meals unless your orthodontist says otherwise.',
        'If something feels sharp or unusual, contact your orthodontic team.',
      ],
      addHour: '\u2795 1 hour',
      subtractHour: '\u2796 1 hour',
    },
    learn: {
      title: 'Meet the tools',
      body: 'Short explainers can make a dental visit feel more predictable and less stressful. These are learning notes, not medical advice.',
      sections: [
        {
          id: 'little-kid-basics',
          title: 'For younger kids',
          body: 'Simple, calm ideas for first visits and daily brushing.',
          ageGroups: ['little-kid'],
          cards: [
            {
              title: 'Mirror',
              tag: 'Dental tool',
              body: 'A tiny mirror helps the dentist peek around corners and shine light where it is hard to see.',
            },
            {
              title: 'Suction straw',
              tag: 'Dental tool',
              body: 'The suction straw is like a little vacuum for water, so it is easier to stay comfortable during a visit.',
            },
            {
              title: 'Toothpaste size',
              tag: 'Healthy habit',
              body: 'Use a grain-of-rice smear before age 3 and a pea-sized amount from ages 3 to 6.',
            },
            {
              title: 'First dental visit',
              tag: 'Parent tip',
              body: 'The first dental visit should happen by the first tooth or first birthday, whichever comes first.',
            },
          ],
        },
        {
          id: 'big-kid-learning',
          title: 'For school-age kids',
          body: 'A little more detail for children ready to learn what happens at the dentist.',
          ageGroups: ['big-kid'],
          cards: [
            {
              title: 'Explorer',
              tag: 'Dental tool',
              body: 'The explorer is a checking tool. It helps the dentist feel the tooth surface and look for spots that need attention.',
            },
            {
              title: 'Scaler',
              tag: 'Dental tool',
              body: 'A scaler helps clean away stuck-on buildup that a toothbrush cannot always reach.',
            },
            {
              title: 'Sealants',
              tag: 'Smile fact',
              body: 'Sealants are like a raincoat for the bumpy tops of back teeth. They help protect molars from cavities.',
            },
          ],
        },
        {
          id: 'teen-ortho',
          title: 'For teens and ortho routines',
          body: 'Short notes that support aligner care and independence.',
          ageGroups: ['teen'],
          cards: [
            {
              title: 'Braces wax',
              tag: 'Ortho help',
              body: 'Orthodontic wax can cover a spot that rubs until your orthodontic team can check it.',
            },
            {
              title: 'Aligner care',
              tag: 'Ortho habit',
              body: 'Use your case, keep aligners clean, and stick to your orthodontist’s wear schedule.',
            },
            {
              title: 'Tray change prep',
              tag: 'Ortho routine',
              body: 'A planned tray-change day can make it easier to stay on track and remember what comes next.',
            },
          ],
        },
        {
          id: 'family-shared',
          title: 'For all families',
          body: 'Helpful notes that work across ages.',
          ageGroups: ['little-kid', 'big-kid', 'teen'],
          cards: [
            {
              title: 'Healthy brushing',
              tag: 'Habit',
              body: 'Brush twice a day for 2 minutes, using gentle circles across every side of each tooth.',
            },
          ],
        },
      ],
    },
    parent: {
      title: 'Parent dashboard',
      body: 'Keep quick notes, watch routines, and switch between profiles without creating online accounts.',
      notesLabel: 'Family notes',
      saveNotes: 'Notes saved on this device.',
      profilesTitle: 'Profiles',
      addProfile: 'Add another profile',
    },
    profileForm: {
      title: 'Create a profile',
      name: 'Name',
      type: 'Profile type',
      ageGroup: 'Age group',
      ageGroupHelp: 'Pick the age band that best matches how this child learns and uses the app.',
      save: 'Save profile',
      previewTitle: 'Profile preview',
      child: 'Child',
      teen: 'Teen',
      littleKid: 'Ages 4 to 7',
      bigKid: 'Ages 8 to 12',
      teenager: 'Ages 13 to 17',
      childDescription: 'Best for younger kids focused on brushing, visits, and tooth milestones.',
      teenDescription: 'Best for older kids or teens using aligners and more independent routines.',
    },
  },
  es: {
    appName: 'SmileSteps',
    tagline: 'Habitos saludables para ninos, adolescentes y padres.',
    heroTitle: 'Pequenas rutinas, sonrisas mas fuertes',
    heroBody:
      'SmileSteps es una prueba de concepto local para rutinas dentales pediatricas y de ortodoncia. Todo se queda en este dispositivo a menos que una version futura cambie eso.',
    createProfile: 'Crear perfil',
    languageLabel: 'Idioma de la app',
    parentView: 'Vista para padres',
    childView: 'Vista infantil',
    tabs: {
      home: 'Inicio',
      brushing: 'Cepillar',
      track: 'Seguir',
      learn: 'Aprender',
      parent: 'Padres',
    },
    home: {
      welcome: 'Hoy es un buen dia para cuidar tu sonrisa.',
      dailyPlan: 'Elige un pequeno logro: cepillarte, registrar un cambio dental, contar tiempo con alineadores o aprender algo nuevo.',
      startHereTitle: 'Empieza aqui',
      startHereBody: 'Esta demo funciona mejor como una app movil. Elige un perfil, toma una tarea rapida y usa las pestanas de abajo para moverte.',
      nextSteps: ['\u2728 Cepillate 2 minutos', '\uD83E\uDDB7 Actualiza un diente', '\u23F1\uFE0F Registra tiempo de alineadores', '\uD83D\uDCA1 Aprende una herramienta'],
      onboardingTitle: 'Bienvenido a SmileSteps',
      onboardingBody: 'Este es un lugar tranquilo y amigable para habitos de cepillado, cambios dentales y rutinas de ortodoncia.',
      onboardingPoints: [
        'Elige un perfil infantil o adolescente.',
        'Usa la pantalla de cepillado para una rutina guiada de 2 minutos.',
        'Explora dientes, ortodoncia y aprendizaje con calma.',
      ],
      onboardingButton: 'Empezar',
      tasksTitle: 'Tareas de hoy',
      activityTitle: 'Actividad reciente',
      emptyActivity: 'Tus actualizaciones recientes apareceran aqui.',
      timerCard: 'Inicia una sesion de cepillado de 2 minutos con guia positiva.',
      toothCard: 'Lleva un registro de dientes de leche, dientes permanentes y logros.',
      orthoCard: 'Mantén tus rutinas de alineadores con recordatorios simples y progreso visible.',
      learnCard: 'Explora explicaciones tranquilas y faciles sobre herramientas dentales comunes.',
    },
    brushing: {
      title: 'Temporizador de 2 minutos',
      body: 'Cepilla con calma, cambia de lado cuando se indique y usa movimientos suaves en circulos.',
      start: '\u25B6\uFE0F Iniciar',
      reset: '\uD83D\uDD04 Reiniciar',
      pause: '\u23F8\uFE0F Pausar',
      resume: '\u25B6\uFE0F Seguir',
      finished: '\uD83C\uDF89 Muy bien! Terminaste dos minutos.',
      encouragement: ['\u2B55 Circulos pequenos', '\uD83D\uDE01 Ahora enfrente', '\uD83E\uDDB7 Ahora las muelas', '\uD83D\uDCAA Ya casi', '\u2728 Final brillante'],
      quadrants: ['\u2196\uFE0F Arriba derecha', '\u2197\uFE0F Arriba izquierda', '\u2199\uFE0F Abajo izquierda', '\u2198\uFE0F Abajo derecha'],
      helperFinished: 'Terminaste cada parte de tu sonrisa.',
      helperPrefix: 'Concentrate en',
      helperSuffix: 'con circulos suaves.',
    },
    teeth: {
      title: 'Registro dental',
      body: 'Toca un lugar para marcar un diente de leche que se cayo o para quitar la marca.',
      hint: 'Este registro es solo educativo para la familia y no ofrece consejo medico.',
      labels: toothLabels,
    },
    ortho: {
      title: 'Habitos de ortodoncia',
      body: 'Registra horas de alineadores y evita olvidar el cambio de bandejas.',
      goal: 'Meta de horas hoy',
      nextChange: 'Proximo cambio',
      progressTitle: 'Progreso de hoy',
      progressStates: {
        strong: '\uD83D\uDCAA Rutina fuerte',
        steady: '\uD83D\uDCC8 Buen avance',
        needsCare: '\uD83D\uDD04 Necesita reinicio',
      },
      nextChangeLabels: {
        today: '\uD83D\uDD34 El cambio es hoy',
        tomorrow: '\uD83D\uDFE1 El cambio es manana',
        inDaysPrefix: '\u23F3 Dias para el proximo cambio',
        overdue: '\u26A0\uFE0F La fecha de cambio ya paso',
      },
      historyTitle: '\uD83D\uDCCB Actividad orto reciente',
      emptyHistory: 'Tus cambios de alineadores y bandejas apareceran aqui.',
      remindersTitle: 'Recordatorios utiles',
      reminders: [
        'Usa los alineadores segun las indicaciones del equipo de ortodoncia.',
        'Quitalos para comer, a menos que te digan otra cosa.',
        'Guarda los alineadores en su estuche, no en una servilleta.',
      ],
      comfortTitle: '\uD83D\uDEDF Consejos de comodidad',
      comfortTips: [
        'Usa un estuche limpio para mantener los alineadores seguros.',
        'El agua fria puede sentirse bien despues de un cambio de bandeja.',
        'Quita los alineadores para comer, a menos que tu ortodoncista diga otra cosa.',
        'Si algo se siente raro o muy molesto, llama a tu equipo de ortodoncia.',
      ],
      addHour: '\u2795 1 hora',
      subtractHour: '\u2796 1 hora',
    },
    learn: {
      title: 'Conoce las herramientas',
      body: 'Las explicaciones cortas pueden hacer que una visita dental se sienta menos estresante. Son notas educativas, no consejo medico.',
      sections: [
        {
          id: 'little-kid-basics',
          title: 'Para peques',
          body: 'Ideas simples y tranquilas para primeras visitas y cepillado diario.',
          ageGroups: ['little-kid'],
          cards: [
            {
              title: 'Espejo',
              tag: 'Herramienta dental',
              body: 'Un pequeno espejo ayuda a ver rincones y a llevar luz a lugares dificiles de mirar.',
            },
            {
              title: 'Succion',
              tag: 'Herramienta dental',
              body: 'La succion funciona como una pequena aspiradora de agua para que la boca se sienta mas comoda.',
            },
            {
              title: 'Cantidad de pasta',
              tag: 'Habito',
              body: 'Usa una mancha del tamano de un grano de arroz antes de los 3 anos y una cantidad del tamano de un guisante entre 3 y 6 anos.',
            },
            {
              title: 'Primera visita dental',
              tag: 'Consejo para padres',
              body: 'La primera visita dental debe ser cuando salga el primer diente o antes del primer cumpleanos.',
            },
          ],
        },
        {
          id: 'big-kid-learning',
          title: 'Para ninos en edad escolar',
          body: 'Un poco mas de detalle para quienes quieren entender mejor la visita dental.',
          ageGroups: ['big-kid'],
          cards: [
            {
              title: 'Explorador',
              tag: 'Herramienta dental',
              body: 'El explorador ayuda a revisar la superficie del diente y encontrar zonas que necesitan atencion.',
            },
            {
              title: 'Escariador',
              tag: 'Herramienta dental',
              body: 'El escariador ayuda a quitar acumulacion pegada que un cepillo no siempre puede alcanzar.',
            },
            {
              title: 'Selladores',
              tag: 'Dato',
              body: 'Los selladores son como un impermeable para la parte con surcos de las muelas. Ayudan a proteger de caries.',
            },
          ],
        },
        {
          id: 'teen-ortho',
          title: 'Para adolescentes y ortodoncia',
          body: 'Notas breves para apoyar alineadores y rutinas mas independientes.',
          ageGroups: ['teen'],
          cards: [
            {
              title: 'Cera',
              tag: 'Ayuda orto',
              body: 'La cera de ortodoncia puede cubrir una zona que roza hasta que el equipo la revise.',
            },
            {
              title: 'Cuidado del alineador',
              tag: 'Habito orto',
              body: 'Usa tu estuche, limpia los alineadores y sigue el horario indicado por tu ortodoncista.',
            },
            {
              title: 'Preparar el cambio',
              tag: 'Rutina orto',
              body: 'Tener un dia de cambio planeado ayuda a seguir el ritmo y recordar el siguiente paso.',
            },
          ],
        },
        {
          id: 'family-shared',
          title: 'Para toda la familia',
          body: 'Recordatorios utiles para cualquier edad.',
          ageGroups: ['little-kid', 'big-kid', 'teen'],
          cards: [
            {
              title: 'Cepillado saludable',
              tag: 'Habito',
              body: 'Cepilla dos veces al dia por 2 minutos con circulos suaves en cada lado del diente.',
            },
          ],
        },
      ],
    },
    parent: {
      title: 'Panel para padres',
      body: 'Guarda notas rapidas, revisa rutinas y cambia entre perfiles sin crear cuentas en linea.',
      notesLabel: 'Notas familiares',
      saveNotes: 'Las notas se guardaron en este dispositivo.',
      profilesTitle: 'Perfiles',
      addProfile: 'Agregar otro perfil',
    },
    profileForm: {
      title: 'Crear un perfil',
      name: 'Nombre',
      type: 'Tipo de perfil',
      ageGroup: 'Grupo de edad',
      ageGroupHelp: 'Elige el grupo que mejor coincide con la edad y la forma de aprender de esta persona.',
      save: 'Guardar perfil',
      previewTitle: 'Vista previa del perfil',
      child: 'Nino',
      teen: 'Adolescente',
      littleKid: 'Edades 4 a 7',
      bigKid: 'Edades 8 a 12',
      teenager: 'Edades 13 a 17',
      childDescription: 'Ideal para peques enfocados en cepillado, visitas y cambios dentales.',
      teenDescription: 'Ideal para mayores o adolescentes con alineadores y rutinas mas independientes.',
    },
  },
};
